steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/crpostgre:${_VERSION}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/crpostgre:${_VERSION}']
images: ['gcr.io/$PROJECT_ID/crpostgre:${_VERSION}']
